name: Deploy Beta

on:
  push:
    branches:
      - beta

jobs:
  deploy_beta:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: hugo --destination /opt/github-dfwhypno/public

      - name: Copy public files to deployment directory
        run: |
          sudo cp -r /opt/github-dfwhypno/public/* /var/www/dfwhypno/www-beta/
          sudo chown -R www-data:www-data /var/www/dfwhypno/www-beta/
