name: Deploy Beta

on:
  push:
    branches:
      - beta

jobs:
  deploy_beta:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Change directory to Hugo project
        run: cd /opt/github-dfwhypno/_work/dfwhypno/dfwhypno
        
      - name: Build Hugo site
        run: hugo --destination /opt/github-dfwhypno/public --environment beta

      - name: Clean destination
        run: rm -rf /var/www/dfwhypno/www-beta/*

      - name: Copy public files to deployment directory
        run: cp -r /opt/github-dfwhypno/public/* /var/www/dfwhypno/www-beta/
